### PR TITLE
Proposed modifications for NF & RS+ AddOns

### PR DESCRIPTION
**Pull request by OnlyLightMatters**
My proposal for NF short names + minor RS+ fixes

### CODE REVIEW

**Comment by Lisias** [comment]
Jesus Christ... It was 11 days already? o.O

Let's finish this job. I'm taking a look on it.

**Review by Lisias — COMMENTED** [review]
There's no need to change the version number if the file format is still the same. Think on it as a "schema"

**Review by Lisias — COMMENTED** [review]
There's a Copy & Paste error :)

**Comment by Lisias** [comment]
I'm changing the target to `dev` because the `master` should include **only** Add'Ons already published.

**Comment by Lisias** [comment]
I will make some fix on them after merging, as I commented above.

**Comment by OnlyLightMatters** [comment]
Hey Lisias. No problem. I had a lot of work lately and I made no progress on supporting any other AddOn. I even had no time to play nor make any videos!

**Pull request merged**
